<?php
/**
 * @author Cristiano Longo
 * @author Mario Alvise Di Bernardo
 */

require("../ConfiscatedAssetsConverter.php");

//Inizializziamo le variabili per generare i due file in output
$str_beni = "";
$str_geo = "";

/******************************************************
 * Create the handles
 */
$assets=fopen('assets.owl','w+') or die('Unable to create file');
$locations=fopen('locations.owl','w+') or die('Unable to create file');
$coordinates=fopen('geometry.owl','w+') or die('Unable to create file');
$all=fopen('assetsAll.owl','w+') or die('Unable to create file');
$log=fopen('log.txt','w+') or die('Unable to create file');

/******************************************************
 * Print headers.
 */
fwrite($assets, file_get_contents('assets_preamble.owl.part'));
fwrite($locations, file_get_contents('locations_preamble.owl.part'));
fwrite($coordinates, file_get_contents('geometry_preamble.owl.part'));
fwrite($all, file_get_contents('assetsAll_preamble.owl.part'));

$timeString="Generated by csv2locnPalermo.php on ".date('d-m-Y-H-i');
fwrite($assets, "<!-- ".$timeString."-->\n");
fwrite($locations, "<!-- ".$timeString."-->\n");
fwrite($coordinates, "<!-- ".$timeString."-->\n");
fwrite($all, "<!-- ".$timeString."-->\n");
fwrite($log, $timeString."\n");

// Iniziamo la lettura
$in=fopen('php://stdin', 'r');
$converter=new ConfiscatedAssetsConverter($assets, $locations, $coordinates, $all, $log);

$count=0;
while( $row = fgetcsv($in,1000,"\t") )
{
	$id=$row[0];
	$street=$row[1];		//Indirizzo
	$number=$row[2];		//Civico
	$description=$row[8];	//Tipologia
	$idL1=$row[5];			//Foglio
	$idL2=$row[6];			//Particella
	$idL3=$row[7];			//Sub
	$ass=$row[9];			//Associazione Assegnataria	

	if (isset($description))
		$descriptionUTF8=utf8_encode($description);
	else 
		$descriptionUTF8="";
		
	if (isset($street))
		$streetUTF8=utf8_encode($street);
	else
		$streetUTF8='';
	
	if (isset($number))
		$numberUTF8=utf8_encode($number);
	else 
		$numberUTF8='';
		
	$converter->convert($count++, $id, $descriptionUTF8, $streetUTF8, $numberUTF8, "Catania");
}

/******************************************************
 * Print footers and close files.
 */
$footer="</rdf:RDF>\n\n";
fwrite($assets, $footer);
fwrite($locations, $footer);
fwrite($coordinates, $footer);
fwrite($all, $footer);
fwrite($log,"Found $count confiscated assets.\n");

fclose($assets);
fclose($locations);
fclose($coordinates);
fclose($all);
fclose($log);	
?>